### ISSUE TITLE
インストール方法の明記

### ISSUE THREAD

**Issue by jiko21** [tascell/sc-tascell#1]
## 概要
今の所、インストール方法(clisp含む)がバラバラになっていて、
非常に面倒。

## 解決策
GitHubのWiki、あるいは`README.md`に明記する。
いずれにせよMarkdown記法で書くことが望ましい。

**Comment by daikikojima** [comment]
一旦 Wiki側のHomeを立てて、そこからinstallationのページ生やします

**Comment by tastasgit** [comment]
We have created README.md and close this issue.
